package pro.javatar.pipeline.service.infra.model

enum InfraTypes {

    RELATIONAL_DATABASE,
    RELATIONAL_DATABASE_WITH_SLAVE,
    NOSQL_DATABASE,
    NOSQL_DATABASE_CLUSTER,
    MESSAGE_BROKER,
    MESSAGE_BROKER_CLUSTER,
    API_GATEWAY_SERVICE,
    API_GATEWAY_STORAGE,
    SERVICE_REGISTRY,
    CONFIGURATION_SERVICE,
    IDENTITY_PROVIDER,
    JENKINS_SLAVE,
    SERVICE_ORCHESTRATION_MASTER,
    SERVICE_ORCHESTRATION_AGENT,
    DNS_SERVICE,
    VPN

}
